export const queryKeys = {
  setup: ['setup-status'] as const,
  session: ['session'] as const,
  categories: ['categories'] as const,
  statuses: ['asset-statuses'] as const,
  tags: ['tags'] as const,
  applicationSettings: ['application-settings'] as const,
  dashboard: (periodDays: number) => ['dashboard', periodDays] as const,
  assetLists: ['assets'] as const,
  assets: (filters: Record<string, unknown> = {}) => ['assets', filters] as const,
  asset: (assetId: string) => ['asset', assetId] as const,
  recycleBin: ['assets', 'recycle-bin'] as const,
  orders: ['orders'] as const,
  order: (orderId: string) => ['order', orderId] as const,
  wishlistLists: ['wishlist'] as const,
  wishlists: (filters: Record<string, unknown> = {}) => ['wishlist', filters] as const,
  wishlist: (itemId: string) => ['wishlist-item', itemId] as const,
  reminders: ['reminders'] as const,
  reminder: (reminderId: string) => ['reminder', reminderId] as const,
  upcomingReminders: ['reminders', 'upcoming'] as const,
  notificationChannels: ['notification-channels'] as const,
  personalApiSettings: ['personal-api-settings'] as const,
  personalAccessTokens: ['personal-access-tokens'] as const,
  subscriptions: ['subscriptions'] as const,
  subscription: (id: string) => ['subscriptions', id] as const,
};
